# Generated by Django 4.2.5 on 2023-11-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0002_alter_member_username_uploadedbook'),
        ('livrowebapp', '0002_member_active'),
    ]

    operations = [
    ]
