# Generated by Django 4.2.5 on 2023-11-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0003_merge_20231127_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='UploadedBook',
        ),
    ]
