# Generated by Django 4.2.5 on 2023-11-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0004_alter_member_username_delete_uploadedbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='active',
        ),
    ]
