# Generated by Django 4.2.5 on 2023-11-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0004_alter_member_username_delete_uploadedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
