# Generated by Django 4.2.5 on 2023-11-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0005_remove_member_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
