# Generated by Django 4.2.5 on 2023-11-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0005_alter_member_active'),
        ('livrowebapp', '0007_remove_member_active'),
    ]

    operations = [
    ]
