# Generated by Django 4.2.5 on 2023-12-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0008_merge_20231128_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('book_cover', models.ImageField(upload_to='book_covers/')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=200)),
                ('book_count', models.IntegerField()),
                ('books', models.ManyToManyField(related_name='libraries', to='livrowebapp.book')),
                ('main_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_libraries', to='livrowebapp.book')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveIntegerField()),
                ('dislikes', models.PositiveIntegerField()),
                ('comments', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='livrowebapp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livrowebapp.member')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='feedbacks',
            field=models.ManyToManyField(related_name='books', to='livrowebapp.feedback'),
        ),
        migrations.AddField(
            model_name='member',
            name='libraries',
            field=models.ManyToManyField(related_name='members', to='livrowebapp.library'),
        ),
    ]
