# Generated by Django 4.2.5 on 2023-12-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0009_book_alter_member_password_alter_member_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='about_user',
            field=models.TextField(default=''),
        ),
    ]
