# Generated by Django 4.2.5 on 2023-12-02 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0010_member_about_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='access_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='livrowebapp.member'),
        ),
    ]
