# Generated by Django 4.2.7 on 2023-12-02 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0011_book_access_link_book_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uploader_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
