# Generated by Django 4.2.5 on 2023-12-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0012_book_uploader_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='book',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='livrowebapp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livrowebapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='livrowebapp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livrowebapp.member')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='livrowebapp.comment'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='livrowebapp.rating'),
        ),
    ]
