# Generated by Django 4.2.5 on 2023-12-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0013_remove_feedback_book_remove_feedback_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
