# Generated by Django 4.2.5 on 2023-12-03 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0015_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 3)),
        ),
    ]
