# Generated by Django 4.2.5 on 2023-12-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0016_alter_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
