# Generated by Django 4.2.5 on 2023-12-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0017_remove_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
