# Generated by Django 4.2.5 on 2023-12-03 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0022_remove_like_book_remove_like_user_remove_rating_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='feedbacks',
        ),
        migrations.RemoveField(
            model_name='book',
            name='like',
        ),
        migrations.CreateModel(
            name='UserFave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livrowebapp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livrowebapp.member')),
            ],
        ),
    ]
