# Generated by Django 4.2.5 on 2023-12-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livrowebapp', '0023_remove_book_feedbacks_remove_book_like_userfave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
